新增迷宮模式(Add new mazes)
YiKaiWu1125/ElecTrap_backend pull request #15
Opened 2022-07-26 19:02 UTC by YiKaiWu1125

+ 目前為簡易版UI (未來可改進)
+ 提供兩關卡可測試(easy,hard)
+ 解決 #4 Add new mazes

2022-07-27 10:23 UTC, asas1asas200 requested changes
There are two problems need to be solved:
+ Are you tested it on your machine, it cannot run on my machine:
  ```shell
  $ python maze_game.py
  video init Image Size: 640 x 480
    video fix Image Size: 1280 x 720
  INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
  Traceback (most recent call last):
    File "/home/zeng/Desktop/ElecTrap_backend/real_mazes/maze_game.py", line 168, in <module>
      begin_maze_gmae(camera_id,picture_name,width,hight)
    File "/home/zeng/Desktop/ElecTrap_backend/real_mazes/maze_game.py", line 150, in begin_maze_gmae
      img,sta,game_begin_time,game_end_time = maze_judgment_status(img,unit8_img,binarization_arr,x,y,sta,game_begin_time,game_end_time)
    File "/home/zeng/Desktop/ElecTrap_backend/real_mazes/maze_game.py", line 59, in maze_judgment_status
      img = draw_maze(img,unit8_img)
    File "/home/zeng/Desktop/ElecTrap_backend/real_mazes/maze_game.py", line 44, in draw_maze
      image = cv2.add(image,unit8_img)
  cv2.error: OpenCV(4.6.0) /io/opencv/modules/core/src/arithm.cpp:647: error: (-209:Sizes of input arguments do not match) The operation is neither 'array op array' (where arrays have the same size and the same number of channels), nor 'array op scalar', nor 'scalar op array' in function 'arithm_op'
  ```
  If this code work for you, show off your python version and pip packages version.
+ Is `easy.png` and `hard.png` the same file?

2022-07-27 10:23 UTC, asas1asas200 commented on real_mazes/maze_game.py
> +    camera_id = 1#'test.mp4'
Consider change to `0` for default camera ID, or pass it by command line arguments.

2022-07-27 10:23 UTC, asas1asas200 commented on real_mazes/maze_game.py
> +def begin_maze_gmae(camera_id,picture_name,width,hight):
Typo `begin_maze_game`.

2022-07-27 10:28 UTC, asas1asas200 commented
Consider rewriting it as class for [OOP](https://en.wikipedia.org/wiki/Object-oriented_programming), this is Python not C/C++.

2022-07-27 13:23 UTC, YiKaiWu1125 commented
Are you tested it on your machine, it cannot run on my machine
`回復: 我的所有電腦上皆可順利執行，至於您無法順離執行原因，應該是您的鏡頭好像只支持到1280 x 720，無法支援到1920*1080 ，而目前本地圖僅支持1920*1080，後續將會更新鏡頭解析度相容性問題`
If this code work for you, show off your python version and pip packages version.
`回復:`
`
absl-py==1.2.0
attrs==21.4.0
click==8.1.3
colorama==0.4.5
cycler==0.11.0
Flask==2.1.2
fonttools==4.34.4
importlib-metadata==4.12.0
itsdangerous==2.1.2
Jinja2==3.1.2
kiwisolver==1.4.4
MarkupSafe==2.1.1
matplotlib==3.5.2
mediapipe==0.8.10.1
numpy==1.21.6
opencv-contrib-python==4.6.0.66
opencv-python==4.6.0.66
packaging==21.3
Pillow==9.2.0
pip==22.2
protobuf==3.20.1
pyparsing==3.0.9
python-dateutil==2.8.2
setuptools==47.1.0
six==1.16.0
typing_extensions==4.3.0
Werkzeug==2.2.0
zipp==3.8.1
`
Is easy.png and hard.png the same file?
`回復:當然不一樣，hard.png的地圖真的超難喔`

2022-07-27 13:34 UTC, asas1asas200 commented
> Are you tested it on your machine, it cannot run on my machine `回復: 我的所有電腦上皆可順利執行，至於您無法順離執行原因，應該是您的鏡頭好像只支持到1280 x 720，無法支援到1920*1080 ，而目前本地圖僅支持1920*1080，後續將會更新鏡頭解析度相容性問題` If this code work for you, show off your python version and pip packages version. `回復:`
> 
> ```
> absl-py==1.2.0
> attrs==21.4.0
> click==8.1.3
> colorama==0.4.5
> cycler==0.11.0
> Flask==2.1.2
> fonttools==4.34.4
> importlib-metadata==4.12.0
> itsdangerous==2.1.2
> Jinja2==3.1.2
> kiwisolver==1.4.4
> MarkupSafe==2.1.1
> matplotlib==3.5.2
> mediapipe==0.8.10.1
> numpy==1.21.6
> opencv-contrib-python==4.6.0.66
> opencv-python==4.6.0.66
> packaging==21.3
> Pillow==9.2.0
> pip==22.2
> protobuf==3.20.1
> pyparsing==3.0.9
> python-dateutil==2.8.2
> setuptools==47.1.0
> six==1.16.0
> typing_extensions==4.3.0
> Werkzeug==2.2.0
> zipp==3.8.1
> ```
> 
> Is easy.png and hard.png the same file? `回復:當然不一樣，hard.png的地圖真的超難喔`

But these look too similar:
![](https://i.imgur.com/kHRZnJZ.png)

2022-07-27 13:36 UTC, asas1asas200 commented
Use `Quote reply` to reply the context next time.
![](https://i.imgur.com/0YnjDcc.png)

2022-07-27 13:37 UTC, asas1asas200 commented
And it seems low fps on my machine, what about yours?

2022-07-27 13:37 UTC, YiKaiWu1125 commented on real_mazes/maze_game.py
> +    camera_id = 1#'test.mp4'
已先改為
`camera_id = 0`

2022-07-27 13:39 UTC, YiKaiWu1125 commented on real_mazes/maze_game.py
> +def begin_maze_gmae(camera_id,picture_name,width,hight):
已更正為 `begin_maze_game`

2022-07-27 13:47 UTC, YiKaiWu1125 commented
> And it seems low fps on my machine, what about yours?

我的跑起來還可以 目測有大於15fps (還是會需要先嵌入fps畫面)

2022-07-27 13:48 UTC, YiKaiWu1125 commented
> Use `Quote reply` to reply the context next time. ![](https://camo.githubusercontent.com/a528a30286c819327bcd63bbf6396d7b96ecf660391f6904da23d420bdd23b7d/68747470733a2f2f692e696d6775722e636f6d2f30596e6a4463632e706e67)

ok 好的~~

2022-07-27 13:50 UTC, asas1asas200 commented
> > And it seems low fps on my machine, what about yours?
> 
> 我的跑起來還可以 目測有大於15fps (還是會需要先嵌入計算fps的畫面)

Nice to have.

This PR will be merged after doing this.

2022-07-28 15:15 UTC, YiKaiWu1125 commented
> > > And it seems low fps on my machine, what about yours?
> > 
> > 
> > 我的跑起來還可以 目測有大於15fps (還是會需要先嵌入計算fps的畫面)
> 
> Nice to have.
> 
> This PR will be merged after doing this.

已新增fps資訊 在畫面中

2022-07-28 15:37 UTC, merged